# Libraries
Numpy,  pandas, Matplotlib, Seaborn

In [1]:
import numpy as np

# 1- D array

In [2]:
myarr= np.array([1,2,3,4])

In [3]:
print(myarr)

[1 2 3 4]


In [4]:
print(type(myarr))

<class 'numpy.ndarray'>


In [5]:
myarr.ndim        #   to check dimention of array

1

In [6]:
arr= np.array([1])

In [7]:
print(arr)

[1]


In [8]:
print(type(myarr))

<class 'numpy.ndarray'>


In [9]:
arr.ndim

1

# 2-D array

In [10]:
ar= np.array([[1,2,3], [2,3,4]])

In [11]:
print(ar)

[[1 2 3]
 [2 3 4]]


In [12]:
ar.ndim                #  2-D array

2

In [13]:
a= np.array([[1,2,3], [2,3,4], [5,6,7]])

In [14]:
a.ndim

2

# 3-D array

In [15]:
x= np.array([[[1,2,3], [3,4,5], [5,6,7]]])

In [16]:
print(x)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]]


In [17]:
x.ndim          # 3-D  array

3

In [18]:
x= np.array([[[1,2,3], [3,4,5]]])

In [19]:
x

array([[[1, 2, 3],
        [3, 4, 5]]])

In [20]:
x.ndim

3

# Numpy function - 

# zeros

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.zeros((2,4))         # 2 row , 4 column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros((2, 4, 3))        # 2 matrix and 4 row 3 column

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# one

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((2,1,10))          # 2 matrix   and 1 row   10  column

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [28]:
np.ones((2,3,5))         # 3 row  and 5 column

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# identity

In [29]:
np.identity(2)     # two by two matrix

array([[1., 0.],
       [0., 1.]])

In [30]:
np.identity(3)          # three by three matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.identity(4)         #   4 by 4 matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Arange

In [32]:
np.arange(4)       # (0 to n-1)

array([0, 1, 2, 3])

In [33]:
np.arange(4,10)       # 4 to 9

array([4, 5, 6, 7, 8, 9])

In [34]:
np.arange(4,10,2)

array([4, 6, 8])

In [35]:
np.arange(10,4,-2)

array([10,  8,  6])

# Empty

In [36]:
np.empty(7)            #  generate a random number

array([0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.empty(3)

array([1., 1., 1.])

In [38]:
np.empty((5,2))     # 5 row 2 column

array([[ 1.42176954e-311,  6.95269975e-310],
       [ 4.78829962e+174,  1.42176954e-311],
       [ 6.95269975e-310, -3.92969635e+235],
       [ 1.42176954e-311,  6.95269974e-310],
       [ 9.67350779e+121,  1.42176954e-311]])

# Linspace

In [39]:
np.linspace(2,4)     # Generate a random number between two range

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [40]:
np.linspace(2,6,3)   #    3 stopez  , between 3  to 6

array([2., 4., 6.])

In [41]:
np.linspace(2,6,7)         #   7 stopez

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        ])

# Axis =  0
# Axis = 1

In [36]:
ar1= np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [37]:
print(ar1)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [38]:
ar1.sum()    # sum of total number  from matrix

45

In [39]:
ar1.sum(axis=1)        # axis=1   for column

array([[12, 15, 18]])

In [41]:
ar1.sum(axis=0)        # axis=0   for row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Transpose

In [47]:
import numpy as np

In [48]:
a= np.array([[10,20,30], [23,34,45]])

In [49]:
a

array([[10, 20, 30],
       [23, 34, 45]])

In [50]:
a.T         # transpose of matrix

array([[10, 23],
       [20, 34],
       [30, 45]])

# Min & Max

In [51]:
array= np.array([[10,20,30], [11,22,33]])

In [52]:
print(array)

[[10 20 30]
 [11 22 33]]


In [53]:
array.max()        # maximum  number present in array

33

In [54]:
array.min()        # minimum number present in array

10

# argsort

In [3]:
import numpy as np

In [18]:
arr= np.array([[[6,5,4],[4,1,8],[7,10,9]]])

In [19]:
arr

array([[[ 6,  5,  4],
        [ 4,  1,  8],
        [ 7, 10,  9]]])

In [20]:
#arr.sort()

In [21]:
#arr

In [22]:
arr.argsort()    # to find index number    (first short then print index)

array([[[2, 1, 0],
        [1, 0, 2],
        [0, 2, 1]]], dtype=int64)

In [23]:
arr.sort()

In [29]:
arr

array([[[ 4,  5,  6],
        [ 1,  4,  8],
        [ 7,  9, 10]]])

In [30]:
arr.argsort()            # find index 

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]], dtype=int64)

# sum

In [45]:
arr

array([[[ 4,  5,  6],
        [ 1,  4,  8],
        [ 7,  9, 10]]])

In [46]:
arr.sum(axis=0)                 # (axis= 0)  for  row

array([[ 4,  5,  6],
       [ 1,  4,  8],
       [ 7,  9, 10]])

In [47]:
arr.sum(axis=1)                 # (axis= 1) for column

array([[12, 18, 24]])

# Q.1- write a numpy program to create a 3*3 matrix 
# with value ranging from 2 to 10

In [48]:
import numpy as np
a= np.array([[[1,2,3],[3,4,5],[7,9,8]]])
print(a)
print()
print("dimention=",a.ndim)

[[[1 2 3]
  [3 4 5]
  [7 9 8]]]

dimention= 3


# Q.2- write a numpy program to create null vector 
#  of size 10 and update sixth value to 11

In [51]:
array= np.zeros(10)
print(array)
array[5]= 11
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


# Q3. write a numpy program to create an empty array

In [52]:
ar= np.array([])
print(ar)

[]
